# Chaz's imports from ~/.bashrc
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias 000='chmod -R 000'
alias 644='chmod -R 644'
alias 666='chmod -R 666'
alias 755='chmod -R 755'
alias 777='chmod -R 777'
alias bd='cd "$OLDPWD"'
alias cd..='cd ..'
alias cl='clear'
alias h='history | grep '
alias home='cd ~'
alias chx='chmod +x'
alias chax='chmod a+x'
alias v='nvim .'
alias vim='nvim'
alias y='yazi'
alias vimdiff='nvim -d'
alias tree='tree -C'
# alias fzf='fzf --layout=reverse --height=80%'

